import { readFileSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const root = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const target = resolve(root, "src", "generated-version.ts");

function pkgVersion(name) {
  try {
    const version = JSON.parse(readFileSync(resolve(root, "node_modules", name, "package.json"), "utf8")).version;
    if (version) return version;
  } catch {
    // Fall through to the declared range.
  }
  return pkg.dependencies?.[name] ?? pkg.devDependencies?.[name] ?? "unknown";
}

const pkg = JSON.parse(readFileSync(resolve(root, "package.json"), "utf8"));
const version = process.env.APP_VERSION || pkg.version || "dev";

const content = [
  "// Generated by scripts/write-version.mjs. Do not edit.",
  `export const appVersion = ${JSON.stringify(version)};`,
  `export const appRevision = ${JSON.stringify(process.env.VCS_REF || "unknown")};`,
  `export const appBuildDate = ${JSON.stringify(process.env.BUILD_DATE || "unknown")};`,
  "export const appStack = {",
  `  react: ${JSON.stringify(pkgVersion("react"))},`,
  `  typescript: ${JSON.stringify(pkgVersion("typescript"))},`,
  `  vite: ${JSON.stringify(pkgVersion("vite"))},`,
  `  caddy: ${JSON.stringify("2.10")}`,
  "};",
  "",
].join("\n");

// Only write when the content actually changed, so unchanged `npm test` /
// `npm run build` runs leave the file (and tsc/vite incremental caches)
// untouched.
let existing = "";
try {
  existing = readFileSync(target, "utf8");
} catch {
  // File does not exist yet — generate it.
}
if (existing !== content) {
  writeFileSync(target, content);
}
