CREATE TABLE IF NOT EXISTS video_adjust (
  media_id INTEGER PRIMARY KEY REFERENCES media(id) ON DELETE CASCADE,
  brightness REAL NOT NULL DEFAULT 1.0,
  hue REAL NOT NULL DEFAULT 0.0,
  saturation REAL NOT NULL DEFAULT 1.0,
  gamma REAL NOT NULL DEFAULT 1.0
);