CREATE TABLE IF NOT EXISTS video_adjust (
  media_id BIGINT PRIMARY KEY REFERENCES media(id) ON DELETE CASCADE,
  brightness DOUBLE PRECISION NOT NULL DEFAULT 1.0,
  hue DOUBLE PRECISION NOT NULL DEFAULT 0.0,
  saturation DOUBLE PRECISION NOT NULL DEFAULT 1.0,
  gamma DOUBLE PRECISION NOT NULL DEFAULT 1.0
);